'use client';

import { CompanyRegistration } from '@/types/company.types';
import { ShieldCheck, AlertTriangle, Clock } from 'lucide-react';

interface RegistrationTableProps {
  registrations: CompanyRegistration[];
  }

  export function RegistrationTable({ registrations }: RegistrationTableProps) {
    const calculateExpirationStatus = (expiryDateStr: string) => {
        const today = new Date();
            const expiry = new Date(expiryDateStr);
                const diffTime = expiry.getTime() - today.getTime();
                    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

                        if (diffDays < 0) {
                              return { status: 'EXPIRED', color: 'bg-red-500/10 text-red-400 border-red-500/30', label: 'Expired', days: Math.abs(diffDays) };
                                  } else if (diffDays <= 60) {
                                        return { status: 'WARNING', color: 'bg-amber-500/10 text-amber-400 border-amber-500/30', label: `Expires in ${diffDays} days`, days: diffDays };
                                            } else {
                                                  return { status: 'VALID', color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30', label: 'Valid / Compliant', days: diffDays };
                                                      }
                                                        };

                                                          return (
                                                              <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
                                                                    <div className="p-4 border-b border-slate-800 flex justify-between items-center">
                                                                            <div>
                                                                                      <h2 className="text-base font-semibold text-white">Statutory & Export Registrations</h2>
                                                                                                <p className="text-xs text-slate-400">NTN, WEBOC, TDAP, Halal, & Phytosanitary Credentials</p>
                                                                                                        </div>
                                                                                                              </div>

                                                                                                                    <div className="overflow-x-auto">
                                                                                                                            <table className="w-full text-left border-collapse text-sm">
                                                                                                                                      <thead>
                                                                                                                                                  <tr className="bg-slate-800/50 border-b border-slate-800 text-xs font-semibold uppercase text-slate-400">
                                                                                                                                                                <th className="p-4">Type</th>
                                                                                                                                                                              <th className="p-4">Registration No.</th>
                                                                                                                                                                                            <th className="p-4">Issuing Authority</th>
                                                                                                                                                                                                          <th className="p-4">Issue Date</th>
                                                                                                                                                                                                                        <th className="p-4">Expiry Date</th>
                                                                                                                                                                                                                                      <th className="p-4">Compliance Status</th>
                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                                                                      <tbody className="divide-y divide-slate-800">
                                                                                                                                                                                                                                                                                  {registrations.map((reg) => {
                                                                                                                                                                                                                                                                                                const indicator = calculateExpirationStatus(reg.expiry_date);
                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                              <tr key={reg.id} className="hover:bg-slate-800/30 transition">
                                                                                                                                                                                                                                                                                                                                                <td className="p-4 font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                                    {reg.registration_type.replace(/_/g, ' ')}
                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                        <td className="p-4 text-slate-300 font-mono">{reg.registration_number}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                          <td className="p-4 text-slate-400">{reg.issuing_authority}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <td className="p-4 text-slate-400 text-xs">{reg.issue_date}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="p-4 text-slate-300 text-xs font-medium">{reg.expiry_date}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold border ${indicator.color}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {indicator.status === 'VALID' && <ShieldCheck className="h-3.5 w-3.5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {indicator.status === 'WARNING' && <Clock className="h-3.5 w-3.5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {indicator.status === 'EXPIRED' && <AlertTriangle className="h-3.5 w-3.5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {indicator.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }