'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { ShieldCheck, Lock, Mail, AlertCircle } from 'lucide-react';

export default function LoginPage() {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [error, setError] = useState<string | null>(null);
        const [loading, setLoading] = useState(false);
          const router = useRouter();
            const supabase = createClient();

              const handleLogin = async (e: React.FormEvent) => {
                  e.preventDefault();
                      setError(null);
                          setLoading(true);

                              const { error: authError } = await supabase.auth.signInWithPassword({
                                    email,
                                          password,
                                              });

                                                  if (authError) {
                                                        setError(authError.message);
                                                              setLoading(false);
                                                                    return;
                                                                        }

                                                                            router.push('/dashboard');
                                                                                router.refresh();
                                                                                  };

                                                                                    return (
                                                                                        <div className="min-h-screen bg-slate-900 flex flex-col justify-center items-center px-4 sm:px-6 lg:px-8">
                                                                                              <div className="sm:mx-auto sm:w-full sm:max-w-md text-center">
                                                                                                      <div className="inline-flex items-center justify-center p-3 bg-green-600/10 rounded-xl mb-4 border border-green-500/20">
                                                                                                                <ShieldCheck className="h-10 w-10 text-green-500" />
                                                                                                                        </div>
                                                                                                                                <h2 className="text-3xl font-extrabold text-white tracking-tight">
                                                                                                                                          Safaa Agro Farms
                                                                                                                                                  </h2>
                                                                                                                                                          <p className="mt-1 text-sm text-slate-400">
                                                                                                                                                                    International Export Operations ERP System
                                                                                                                                                                            </p>
                                                                                                                                                                                  </div>

                                                                                                                                                                                        <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
                                                                                                                                                                                                <div className="bg-slate-800/80 backdrop-blur border border-slate-700/50 py-8 px-6 shadow-2xl rounded-xl sm:px-10">
                                                                                                                                                                                                          {error && (
                                                                                                                                                                                                                      <div className="mb-4 bg-red-500/10 border border-red-500/30 rounded-lg p-3 text-sm text-red-400 flex items-center gap-2">
                                                                                                                                                                                                                                    <AlertCircle className="h-4 w-4 flex-shrink-0" />
                                                                                                                                                                                                                                                  <span>{error}</span>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                  <form className="space-y-6" onSubmit={handleLogin}>
                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300">
                                                                                                                                                                                                                                                                                                                            Official Email
                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                        <div className="mt-2 relative rounded-md shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                                                                                                                                                                                                                                                                                                                                                          <Mail className="h-4 w-4 text-slate-400" />
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                            type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="block w-full pl-10 bg-slate-900 border border-slate-700 rounded-lg py-2.5 text-white text-sm focus:ring-2 focus:ring-green-500 focus:border-transparent transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="admin@safaaagro.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-2 relative rounded-md shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Lock className="h-4 w-4 text-slate-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="block w-full pl-10 bg-slate-900 border border-slate-700 rounded-lg py-2.5 text-white text-sm focus:ring-2 focus:ring-green-500 focus:border-transparent transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full flex justify-center py-3 px-4 border border-transparent rounded-lg text-sm font-semibold text-white bg-green-600 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:opacity-50 transition shadow-lg shadow-green-600/20"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? 'Authenticating System...' : 'Sign In to Portal'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }