'use client';

import { ExportShipmentSummary } from '@/types/dashboard.types';
import { Anchor, Plane, ArrowRight } from 'lucide-react';

interface ActiveShipmentsTableProps {
  shipments: ExportShipmentSummary[];
  }

  export function ActiveShipmentsTable({ shipments }: ActiveShipmentsTableProps) {
    const getStatusBadge = (status: ExportShipmentSummary['shipment_status']) => {
        switch (status) {
              case 'IN_TRANSIT':
                      return 'bg-blue-500/10 text-blue-400 border-blue-500/30';
                            case 'LOADING':
                                    return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
                                          case 'DELIVERED':
                                                  return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
                                                        default:
                                                                return 'bg-slate-800 text-slate-400 border-slate-700';
                                                                    }
                                                                      };

                                                                        return (
                                                                            <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
                                                                                  <div className="p-4 border-b border-slate-800">
                                                                                          <h3 className="text-base font-bold text-white">Active International Export Logistics</h3>
                                                                                                  <p className="text-xs text-slate-400">Live reefer container positions, bill of lading references & destination ETAs</p>
                                                                                                        </div>

                                                                                                              <div className="overflow-x-auto">
                                                                                                                      <table className="w-full text-left text-xs">
                                                                                                                                <thead>
                                                                                                                                            <tr className="bg-slate-800/50 border-b border-slate-800 text-slate-400 font-semibold uppercase">
                                                                                                                                                          <th className="p-3.5">Container / Booking</th>
                                                                                                                                                                        <th className="p-3.5">Cargo Description</th>
                                                                                                                                                                                      <th className="p-3.5">Destination Port</th>
                                                                                                                                                                                                    <th className="p-3.5">Vessel / Air Carrier</th>
                                                                                                                                                                                                                  <th className="p-3.5">Set Temp</th>
                                                                                                                                                                                                                                <th className="p-3.5">ETA</th>
                                                                                                                                                                                                                                              <th className="p-3.5">Status</th>
                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                    </thead>
                                                                                                                                                                                                                                                                              <tbody className="divide-y divide-slate-800">
                                                                                                                                                                                                                                                                                          {shipments.map((shipment) => (
                                                                                                                                                                                                                                                                                                        <tr key={shipment.id} className="hover:bg-slate-800/30 transition">
                                                                                                                                                                                                                                                                                                                        <td className="p-3.5 font-mono font-bold text-white">
                                                                                                                                                                                                                                                                                                                                          {shipment.container_number}
                                                                                                                                                                                                                                                                                                                                                            <span className="block text-[10px] text-slate-500 font-normal">{shipment.booking_reference}</span>
                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                            <td className="p-3.5 font-medium text-slate-300">{shipment.cargo_type}</td>
                                                                                                                                                                                                                                                                                                                                                                                                            <td className="p-3.5 text-slate-300 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                              {shipment.destination_port}
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="block text-[10px] text-slate-400 font-normal">{shipment.destination_country}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td className="p-3.5 text-slate-400 flex items-center gap-1.5 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {shipment.vessel_or_flight.toLowerCase().includes('qr') ? <Plane className="h-3.5 w-3.5 text-blue-400" /> : <Anchor className="h-3.5 w-3.5 text-cyan-400" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {shipment.vessel_or_flight}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className="p-3.5 font-mono text-cyan-400 font-bold">{shipment.reefer_set_temp_c}°C</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className="p-3.5 font-mono text-slate-300">{shipment.eta_date}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className="p-3.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={`inline-block px-2.5 py-1 rounded-full text-[10px] font-bold border ${getStatusBadge(shipment.shipment_status)}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {shipment.shipment_status.replace(/_/g, ' ')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }