'use client';

import { ExecutiveKPIs } from '@/types/dashboard.types';
import { DollarSign, Ship, Snowflake, AlertOctagon, Wallet, ShieldAlert } from 'lucide-react';

interface KPIMetricCardsProps {
  kpis: ExecutiveKPIs | null;
  }

  export function KPIMetricCards({ kpis }: KPIMetricCardsProps) {
    const formatPKR = (val: number | undefined) => {
        if (!val) return 'PKR 0.00';
            return `PKR ${val.toLocaleString('en-PK', { maximumFractionDigits: 0 })}`;
              };

                return (
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
                          {/* Revenue YTD */}
                                <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                        <div className="flex justify-between items-center text-slate-400 mb-1">
                                                  <span className="text-[11px] uppercase font-bold tracking-wider">YTD Revenue</span>
                                                            <DollarSign className="h-4 w-4 text-emerald-400" />
                                                                    </div>
                                                                            <p className="text-lg font-black text-white">{formatPKR(kpis?.total_revenue_ytd)}</p>
                                                                                    <span className="text-[10px] text-emerald-400 font-medium">Recorded Sales Performance</span>
                                                                                          </div>

                                                                                                {/* Active Export Shipments */}
                                                                                                      <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                                                                                              <div className="flex justify-between items-center text-slate-400 mb-1">
                                                                                                                        <span className="text-[11px] uppercase font-bold tracking-wider">Active Shipments</span>
                                                                                                                                  <Ship className="h-4 w-4 text-blue-400" />
                                                                                                                                          </div>
                                                                                                                                                  <p className="text-xl font-black text-white">{kpis?.active_shipments_count ?? 0} Reefer Containers</p>
                                                                                                                                                          <span className="text-[10px] text-blue-400 font-medium">Sea & Air Freight in Motion</span>
                                                                                                                                                                </div>

                                                                                                                                                                      {/* Cold Storage Holdings */}
                                                                                                                                                                            <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                                                                                                                                                                    <div className="flex justify-between items-center text-slate-400 mb-1">
                                                                                                                                                                                              <span className="text-[11px] uppercase font-bold tracking-wider">Cold Storage Val.</span>
                                                                                                                                                                                                        <Snowflake className="h-4 w-4 text-cyan-400" />
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                        <p className="text-lg font-black text-white">{formatPKR(kpis?.total_inventory_value)}</p>
                                                                                                                                                                                                                                <span className="text-[10px] text-cyan-400 font-medium">Chilled & Frozen Assets</span>
                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                            {/* Cold Chain Alerts */}
                                                                                                                                                                                                                                                  <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                                                                                                                                                                                                                                          <div className="flex justify-between items-center text-slate-400 mb-1">
                                                                                                                                                                                                                                                                    <span className="text-[11px] uppercase font-bold tracking-wider">Thermal Alerts</span>
                                                                                                                                                                                                                                                                              <AlertOctagon className="h-4 w-4 text-amber-400" />
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                              <p className="text-xl font-black text-white">{kpis?.active_cold_storage_alerts ?? 0} Breaches</p>
                                                                                                                                                                                                                                                                                                      <span className={`text-[10px] font-medium ${(kpis?.active_cold_storage_alerts ?? 0) > 0 ? 'text-amber-400' : 'text-slate-500'}`}>
                                                                                                                                                                                                                                                                                                                {(kpis?.active_cold_storage_alerts ?? 0) > 0 ? 'Requires Immediate Action' : 'All Facilities Nominal'}
                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                    {/* Liquid Bank Balances */}
                                                                                                                                                                                                                                                                                                                                          <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between items-center text-slate-400 mb-1">
                                                                                                                                                                                                                                                                                                                                                            <span className="text-[11px] uppercase font-bold tracking-wider">Liquid Cash</span>
                                                                                                                                                                                                                                                                                                                                                                      <Wallet className="h-4 w-4 text-green-400" />
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-lg font-black text-white">{formatPKR(kpis?.liquid_cash_pkr)}</p>
                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-[10px] text-slate-400 font-medium">Available Cash in Banks</span>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                          {/* Liabilities / Pending Payables */}
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between items-center text-slate-400 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[11px] uppercase font-bold tracking-wider">Pending Liabilities</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <ShieldAlert className="h-4 w-4 text-red-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-lg font-black text-white">{formatPKR(kpis?.pending_payables_pkr)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-[10px] text-red-400 font-medium">Supplier & Refinance Outflows</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }