-- Safaa Agro Farms ERP - Sprint 2 Database Schema (Company Profile & Financial Master)

-- Statutory Registration Types for Pakistani Export Business
CREATE TYPE registration_type AS ENUM (
    'NTN',
        'SALES_TAX',
            'WEBOC',
                'CHAMBER_OF_COMMERCE',
                    'TDAP',
                        'HALAL',
                            'PHYTOSANITARY',
                                'ANIMAL_QUARANTINE_DEPARTMENT',
                                    'OTHER'
                                    );

                                    -- Asset Categories
                                    CREATE TYPE asset_category AS ENUM (
                                        'WAREHOUSE',
                                            'COLD_STORAGE',
                                                'VEHICLE',
                                                    'MACHINERY',
                                                        'LAND_PLOT',
                                                            'OFFICE_EQUIPMENT'
                                                            );

                                                            -- Company Profile Core Master Table
                                                            CREATE TABLE public.company_profile (
                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                    company_name TEXT NOT NULL DEFAULT 'Safaa Agro Farms (Pvt.) Ltd.',
                                                                        logo_url TEXT,
                                                                            website TEXT NOT NULL DEFAULT 'https://www.safaaagro.com',
                                                                                primary_email TEXT NOT NULL DEFAULT 'info@safaaagro.com',
                                                                                    primary_phone TEXT NOT NULL DEFAULT '+92 42 35780000',
                                                                                        address TEXT NOT NULL DEFAULT 'Lahore, Punjab, Pakistan',
                                                                                            financial_year_start DATE NOT NULL DEFAULT '2025-07-01',
                                                                                                financial_year_end DATE NOT NULL DEFAULT '2026-06-30',
                                                                                                    total_tax_paid NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
                                                                                                        yearly_budget NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
                                                                                                            yearly_profit_loss NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
                                                                                                                total_products INT NOT NULL DEFAULT 0,
                                                                                                                    total_warehouses INT NOT NULL DEFAULT 0,
                                                                                                                        total_cold_storages INT NOT NULL DEFAULT 0,
                                                                                                                            total_vehicles INT NOT NULL DEFAULT 0,
                                                                                                                                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                );

                                                                                                                                -- Statutory Registrations Tracking Table
                                                                                                                                CREATE TABLE public.company_registrations (
                                                                                                                                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                        company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                            registration_type registration_type NOT NULL,
                                                                                                                                                registration_number TEXT NOT NULL,
                                                                                                                                                    issuing_authority TEXT NOT NULL,
                                                                                                                                                        issue_date DATE NOT NULL,
                                                                                                                                                            expiry_date DATE NOT NULL,
                                                                                                                                                                document_url TEXT,
                                                                                                                                                                    is_active BOOLEAN NOT NULL DEFAULT true,
                                                                                                                                                                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                                                                                                                                                                            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                            );

                                                                                                                                                                            -- Utility Connections Tracking Table
                                                                                                                                                                            CREATE TABLE public.company_utilities (
                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                    company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                                                                        utility_type TEXT NOT NULL, -- e.g., 'LESCO Electricity', 'SNGPL Gas', 'Industrial Water'
                                                                                                                                                                                            consumer_number TEXT NOT NULL,
                                                                                                                                                                                                meter_number TEXT,
                                                                                                                                                                                                    monthly_avg_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
                                                                                                                                                                                                        is_active BOOLEAN NOT NULL DEFAULT true,
                                                                                                                                                                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                                                            );

                                                                                                                                                                                                            -- Capital Investments Table
                                                                                                                                                                                                            CREATE TABLE public.company_investments (
                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                    company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                                                                                                        investor_name TEXT NOT NULL,
                                                                                                                                                                                                                            investment_amount NUMERIC(15, 2) NOT NULL,
                                                                                                                                                                                                                                investment_date DATE NOT NULL,
                                                                                                                                                                                                                                    equity_percentage NUMERIC(5, 2) DEFAULT 0.00,
                                                                                                                                                                                                                                        description TEXT,
                                                                                                                                                                                                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                            -- Asset Ledger Table
                                                                                                                                                                                                                                            CREATE TABLE public.company_assets (
                                                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                    company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                        asset_name TEXT NOT NULL,
                                                                                                                                                                                                                                                            category asset_category NOT NULL,
                                                                                                                                                                                                                                                                valuation NUMERIC(15, 2) NOT NULL,
                                                                                                                                                                                                                                                                    acquisition_date DATE NOT NULL,
                                                                                                                                                                                                                                                                        location TEXT NOT NULL,
                                                                                                                                                                                                                                                                            status TEXT NOT NULL DEFAULT 'OPERATIONAL',
                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                -- Liabilities Table
                                                                                                                                                                                                                                                                                CREATE TABLE public.company_liabilities (
                                                                                                                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                                        company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                            lender_or_creditor TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                amount NUMERIC(15, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                    due_date DATE NOT NULL,
                                                                                                                                                                                                                                                                                                        status TEXT NOT NULL DEFAULT 'PENDING',
                                                                                                                                                                                                                                                                                                            description TEXT,
                                                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                -- Bank Accounts Register Table
                                                                                                                                                                                                                                                                                                                CREATE TABLE public.company_bank_accounts (
                                                                                                                                                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                                                                        company_id UUID NOT NULL REFERENCES public.company_profile(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                                                            bank_name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                account_title TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                    account_number TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                        iban TEXT NOT NULL UNIQUE,
                                                                                                                                                                                                                                                                                                                                            swift_code TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                branch_code TEXT,
                                                                                                                                                                                                                                                                                                                                                    current_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
                                                                                                                                                                                                                                                                                                                                                        currency TEXT NOT NULL DEFAULT 'PKR',
                                                                                                                                                                                                                                                                                                                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                            -- Indexes for Swift Query Processing
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_company_registrations_expiry ON public.company_registrations(expiry_date);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_company_assets_category ON public.company_assets(category);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_company_bank_accounts_iban ON public.company_bank_accounts(iban);

                                                                                                                                                                                                                                                                                                                                                            -- Row Level Security
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_profile ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_registrations ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_utilities ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_investments ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_assets ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_liabilities ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                            ALTER TABLE public.company_bank_accounts ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                            -- Read Policies: Authenticated users can view company profile details
                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Authenticated users can view company profile"
                                                                                                                                                                                                                                                                                                                                                                ON public.company_profile FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Authenticated users can view registrations"
                                                                                                                                                                                                                                                                                                                                                                    ON public.company_registrations FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Authenticated users can view utilities"
                                                                                                                                                                                                                                                                                                                                                                        ON public.company_utilities FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Authenticated users can view investments"
                                                                                                                                                                                                                                                                                                                                                                            ON public.company_investments FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Authenticated users can view assets"
                                                                                                                                                                                                                                                                                                                                                                                ON public.company_assets FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Authenticated users can view liabilities"
                                                                                                                                                                                                                                                                                                                                                                                    ON public.company_liabilities FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Authenticated users can view bank accounts"
                                                                                                                                                                                                                                                                                                                                                                                        ON public.company_bank_accounts FOR SELECT TO authenticated USING (true);

                                                                                                                                                                                                                                                                                                                                                                                        -- Write Policies: Restricted to ADMIN and FINANCE roles
                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Admin & Finance can modify company profile"
                                                                                                                                                                                                                                                                                                                                                                                            ON public.company_profile FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                USING (
                                                                                                                                                                                                                                                                                                                                                                                                        EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN')
                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Admin & Finance can modify registrations"
                                                                                                                                                                                                                                                                                                                                                                                                                                                ON public.company_registrations FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                    USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                            EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN', 'ROLE_DOCS')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Admin & Finance can modify investments"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ON public.company_investments FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Admin & Finance can modify assets"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ON public.company_assets FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Admin & Finance can modify liabilities"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ON public.company_liabilities FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Admin & Finance can modify bank accounts"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ON public.company_bank_accounts FOR ALL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT 1 FROM public.user_profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE id = auth.uid() AND role IN ('ROLE_ADMIN', 'ROLE_FIN')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Dynamic View: Automated Calculation of Total Company Worth & Financial Balance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE OR REPLACE VIEW public.vw_company_financial_summary AS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cp.id AS company_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cp.company_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            COALESCE(SUM(DISTINCT ci.investment_amount), 0) AS total_investment,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                COALESCE(SUM(DISTINCT ca.valuation), 0) AS total_assets,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    COALESCE(SUM(DISTINCT cl.amount), 0) AS total_liabilities,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        COALESCE(SUM(DISTINCT cba.current_balance), 0) AS total_cash_in_banks,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    COALESCE(SUM(DISTINCT ca.valuation), 0) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            COALESCE(SUM(DISTINCT cba.current_balance), 0) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    COALESCE(SUM(DISTINCT cl.amount), 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) AS net_company_worth
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FROM public.company_profile cp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LEFT JOIN public.company_investments ci ON cp.id = ci.company_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LEFT JOIN public.company_assets ca ON cp.id = ca.company_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LEFT JOIN public.company_liabilities cl ON cp.id = cl.company_id AND cl.status = 'PENDING'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LEFT JOIN public.company_bank_accounts cba ON cp.id = cba.company_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        GROUP BY cp.id, cp.company_name;